title: Andrews Kangah
logo: /assets/img/headshot_circle.jpeg
description: |
      you know what spiderman does for his day job? web design.
      I do spiderman's job and a lot more
theme: jekyll-theme-minimal
