title: Andrews Kangah
logo: /assets/img/headshot_circle.jpeg
description: |
      do one thing every day that scares you
      Google Scholar: https://scholar.google.com/citations?user=kzs84lEYS_YC&hl=fr
theme: jekyll-theme-minimal
