title: Andrews (Ata) Kangah
logo: /assets/img/headshot_circle.png
description: you know what spiderman does for his day job? web design. I do spiderman's day job plus a whole lot more
theme: jekyll-theme-minimal
